format = '${custom.dirty}$git_branch$directory[\$](bold #ffffff) '#$all'
right_format = "$status" # return value on right side
add_newline = false

[status] # get return value on right side
style = 'bold fg:red'
symbol = '󰌑'
success_symbol = '󰌑'
## alacritty ##
#symbol = '󰌑 '
#success_symbol = '󰌑 '
format = '[$status $symbol]($style)'
disabled = false

[directory]
format = '[\[$path\]]($style)'
style = 'cyan'

[git_branch]
format = '[\[$branch\]]($style)'
style = 'green'

[custom.dirty]
require_repo = true
when = '[[ ! -z $(git status --porcelain) ]]'
symbol = '*'
style = 'red'
format = '[$symbol]($style)'
ignore_timeout = true
shell = ['sh']
