# Colours (Monokai Charcoal)

# Default Colours
[colors.primary]
background = '#000000'
foreground = '#e0dfdf'

# Normal Colours
[colors.normal]
black   = '#000000'
red     = '#f92672'
green   = '#86fa04'
yellow  = '#fd971f'
blue    = '#ae81ff'
magenta = '#e95678'
cyan    = '#66d9ef'
white   = '#f8f8f0'

# Bright Colours
[colors.bright]
black   = '#504945'
red     = '#e95678'
green   = '#a6e12e'
yellow  = '#e6db74'
blue    = '#ae80fe'
magenta = '#f82a71'
cyan    = '#66d8ee'
white   = '#8f908a'
